# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node

name: Node.js CI build & lint

on:
  pull_request:
    branches: [ development, staging, master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: Clean Install
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Run Linter
        run: npm run lint
